/***************************************************************************
*       The OS/2 Warp Toolkit for Software Developers                      *
*       Prentice Hall (C) 1995                                             *
*                                                                          *
*       PROGRAM NAME: SMP7.EXE                                             *
*                                                                          *
*       DESCRIPTION:                                                       *
*       Header file for 32-bit DLL32BIT.DLL                                *
***************************************************************************/

#include "filter.h"

APIRET EXPENTRY MakeSomeNoise( PFINPUTPARMS );
